# Load neofetch
# neofetch

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ]; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ]; then
    PATH="$HOME/.local/bin:$PATH"
fi

# Load Homebrew
if [ -d "/home/linuxbrew/.linuxbrew" ] ; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

# Load pyenv
if [ -d "$HOME/.pyenv" ] ; then
  export PYENV_ROOT="$HOME/.pyenv"
  command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init -)"
fi

# Load nvm
if [ -d "$HOME/.local/share/nvm" ] ; then
  PATH="$HOME/.local/share/nvm/v18.15.0/bin:$PATH"
  PATH="$HOME/node_modules/.bin:$PATH"
fi
